spring:
  application:
    name: "server"
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
springdoc:
  swagger-ui:
    enabled: true
security:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    expiration-time: 3600000